# Generated by Django 3.0.6 on 2020-05-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelname', models.CharField(max_length=30)),
                ('creatorname', models.CharField(max_length=20)),
                ('preference', models.IntegerField()),
                ('onlive', models.BooleanField()),
                ('subscriber', models.IntegerField()),
                ('link1', models.TextField()),
                ('link2', models.TextField()),
                ('link3', models.TextField()),
            ],
        ),
    ]
